### ISSUE TITLE
Migrate to OCP4

### ISSUE THREAD

**Issue by esune** [bcgov/a2a-trust-over-ip-configurations#47]
## Overview
A few profiles use issuer-kit code for their apps, in particular:
- `a2a`: this is a development issuer used to test other applications. Only `dev` and `test` deployments exist.
   As such, in addition to updating the templates, the agent wallets will need to be migrated to the target namespace in OCP4 to ensure a seamless transition.
- `lsbc`: issuer used by an external team (The Law Society of British Columbia). The wallet contents need to be moved to OCP4 for all deployments (`dev`/`test`/`prod`).
- `prime`: issuer used by an external team (MoH Prime). The wallet contents need to be moved to OCP4 for all deployments (`dev`/`test`/`prod`). Additionally, instances of `visual-verifier` are used and need to be migrated over to OCP4.
- `prime-sandbox`: same as prime, just a sandbox development agent (no `test`, no `prod`). Wallet contents need to be moved over to OCP4.
- `tails`: deployments of hosted instances of [indy-tails-server](https://github.com/bcgov/indy-tails-server). PVC contents need to be moved to OCP4.
- `default` and `rev`: instances of [vc-authn-oidc](https://github.com/bcgov/vc-authn-oidc). Content of both wallet and database need to be transferred over to OCP4.
- `backup`: backup-container (postgres) instance. Data needs to be migrated (it can help migrating wallets/databases as it is already backing them up). Needs to be aligned to the latest backup-container configurations in [backup-container](https://github.com/bcgov/backup-container).

## Templates
This is a list of templates to be updated, assigned to the relevant person.

@wadeking98:
- [x] visual-verifier
- [x] issuer-wallet
- [x] issuer-db 
- [x] issuer-agent
- [x] issuer-api
- [x] issuer-web
- [x] backup

@esune:
- [x] agent-rev
- [x] agent
- [x] controller-rev
- [x] controller 
- [x] database
- [x] wallet 
- [x] tails-server 

## Profiles:
This is a list of profiles to be deployed to OCP4, once the templates have been updated, assigned to the relevant person.

@wadeking98:
- [x] a2a
- [x] lsbc
- [x] prime
- [x] prime-sandbox

@esune:
- [x] default
- [x] rev
- [x] tails

**Comment by esune** [comment]
@wadeking98 I have not yet thought through 100% what to do with the pipelines, but I think as a first step ensuring the components based on `issuer-kit` respect the same naming convention we put together for `essential-services-delivery` is a good step. That means the build configurations must be named and labelled the same way (so that they result in exactly the same output) and the deployment configurations must reference those image names.

**Comment by esune** [comment]
@WadeBarnes: as discussed, the tails server was setup and is ready to go in all environments. A new sync of the files stored by the old one will be required before we switch over, as well as coordination to ensure the DNS entries are updated correctly when the time comes.

**Comment by esune** [comment]
All services have been migrated successfully.

@wadeking98 is in the process of migrating the data for `vc-authn` and updating the apps that connect directly to it (e.g.: the visual verifiers) to use the new OCP4 urls.

**Please note:** since we have two instances of `vc-authn` (one supporting revocation and the other not supporting it) make sure the URL used to update the visual-verifier secret(s) is the appropriate one.

**Comment by wadeking98** [comment]
@esune are we free to close this now?

**Comment by esune** [comment]
The only thing left to do is turning off the old tails servers - this coming friday. Maybe we should keep this open until we do that and then wrap up everything.

**Comment by esune** [comment]
Tails servers have been migrated, so this can be closed now.
