### ISSUE TITLE
Deploy Buy BC production agent/controller

### ISSUE THREAD

**Issue by esune** [bcgov/a2a-trust-over-ip-configurations#62]
We need an agent/controller for the production instance of Buy BC.

The agent will be unprivileged, and therefore some manual steps are required to endorse the creation of schema and cred_def.

Checklist:
- [x] Deploy controller and agent in read-only mode (@esune)
- [x] Register DID, schema, cred_def on ledger (@WadeBarnes)
- [x] Restart agent in non-readonly mode (@esune / @WadeBarnes )
- [x] Create connection between Buy BC agent and OrgBook agent (@esune / @WadeBarnes )

**Comment by WadeBarnes** [comment]
DID and VerKey passed along to Stephen to have written to MainNet.

**Comment by swcurran** [comment]
@WadeBarnes that won't work.  The transaction to create the DID must be created by the author, endorsed by the BC Gov endorser (or at least one of them...), and then executed by the author or endorser.  I can't create the DID (well, technically I could, but then the Sovrin Foundation would be charged for the DID, and not BC Gov).

Same sequence has to happen for the Schema and Cred Def.

**Comment by WadeBarnes** [comment]
> @WadeBarnes that won't work. The transaction to create the DID must be created by the author, endorsed by the BC Gov endorser (or at least one of them...), and then executed by the author or endorser. I can't create the DID (well, technically I could, but then the Sovrin Foundation would be charged for the DID, and not BC Gov).

It's been a while since we've written a non-privileged DID to the ledger, I forgot for a moment we did not need `TRUSTEE` signatures.  I checked the `auth-rules` and we should be good to go as described.

**Comment by WadeBarnes** [comment]
The Buy BC `DID, `Schema`, and `Cred-Def` have all been registered on MainNet; https://indyscan.io/txs/SOVRIN_MAINNET/domain?page=1&pageSize=50&filterTxNames=[]&sortFromRecent=true&search=Lmo84oencYUVQPgZC9QHua

**Comment by WadeBarnes** [comment]
The agent was restarted temporarily with `read-only` mode turned off.  Current running in `read-only` mode.

**Comment by WadeBarnes** [comment]
@esune, Everything is ready for the connection with OrgBook to be established.

**Comment by WadeBarnes** [comment]
The steps followed to setup and register the `DID`, `Schema`, and `Cred-Def` for the BuyBC Agent:
[BuyBC-Setup-MainNet.md](https://github.com/bcgov/a2a-trust-over-ip-configurations/files/6874545/BuyBC-Setup-MainNet.md)

**Comment by esune** [comment]
Thank you @WadeBarnes! Is the readme file supposed to be downloadable-only? I can't seem to find it in the repo, it prompts me to download it instead.

I am trying to nail down the agent URL, I suspect we don;t really care, but will get an update shortly.

**Comment by WadeBarnes** [comment]
> Thank you @WadeBarnes! Is the readme file supposed to be downloadable-only? I can't seem to find it in the repo, it prompts me to download it instead.

It's just attached to this issue.

**Comment by esune** [comment]
> 
> 
> > Thank you @WadeBarnes! Is the readme file supposed to be downloadable-only? I can't seem to find it in the repo, it prompts me to download it instead.
> 
> It's just attached to this issue.

😅 I should have figured that out, sorry. Thanks!

**Comment by WadeBarnes** [comment]
This has been done for a while now.
