### ISSUE TITLE
New Client - MDS Test Client

### ISSUE THREAD

**Issue by Jsyro** [bcgov/a2a-trust-over-ip-configurations#71]
We would like to add the VC-authn installation as a IDP to them MDS TEST Keycloak realm. 

I'm familiar with the procedure, but we still need to share certain values. Please me know how/who to connect with.

**Comment by swcurran** [comment]
@esune -- is this small enough that you can do or at least guide?  I'd want a summary of what is to be done.

@WadeBarnes will be involved, I suspect, and @wadeking98 when he gets back from vacay.

**Comment by esune** [comment]
The procedure is:
- we agree on a client id to be used - the recommended/usual value is the name of the realm + environment (e.g.: myrealm-test)
- we receive the URL generated by Keycloak when configuring the new IdP integration
- we receive the secret used when configuring the new IdP integration
- we use this information to set-up a new client using the utility functions in the `openshift/manage` script.

@Jsyro if you send me the information via Rocket.Chat like last time I can work on applying the changes

**Comment by esune** [comment]
@Jsyro client was added.

**Comment by esune** [comment]
Closing as the client was successfully added.
